# Site settings
title: Dev's Log
email: devm33@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Developer of Software, Scientist of Computers, Destroyer of Websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devm33.com" # the base hostname & protocol for your site
twitter_username: devm33
github_username:  devm33

# Build settings
markdown: kramdown
sass:
    style: :compressed
permalink: /:year-:month-:day/

# Plugin settings
safe: true # true for no sym links or custom plugins (github pages uses safe)

