# Site settings
title: Devraj Mehta
email: devm33@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Automate everything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://devm33.com" # the base hostname & protocol for your site

twitter_username: devm33
github_username:  devm33
rss_url: "http://feeds.feedburner.com/devm33"

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: :compressed
permalink: /:year-:month-:day/
include: [".htaccess"]
exclude: [ Gemfile, Gemfile.lock ]

# yaml front matter defaults
defaults:
    -
        scope:
            path: "" # defaults for all pages
        values:
            layout: "post"

# Plugin settings
safe: false # true for no sym links or custom plugins (github pages uses safe)
category_title_prefix: "Posts tagged "
